version: "3.7"
services:
  # Postgres
  db:
    image: postgres
    env_file: .env.dev
    # @see https://www.postgresql.org/docs/9.4/pgstatstatements.html
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    volumes:
      - "db_vol:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  # App
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file: .env.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    depends_on:
      # Starts the `db` service first.
      # Does not wait for Postgres itself to be ready.
      - db

volumes:
  db_vol: {}
